# Generated by Django 5.1.3 on 2024-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_reporter',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='news',
            name='keywords',
        ),
        migrations.AddField(
            model_name='news',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='news', to='news.keyword'),
        ),
    ]
