# Generated by Django 5.1.2 on 2024-10-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='news',
            name='special_category1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='special_category2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='special_feature1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='special_feature2',
        ),
    ]
