# Generated by Django 5.1.2 on 2024-10-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_visits', models.IntegerField()),
                ('social_visits', models.IntegerField()),
                ('bounce_rate', models.FloatField()),
                ('page_views', models.JSONField()),
            ],
        ),
    ]
