# Generated by Django 5.1.3 on 2024-11-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
