# Generated by Django 5.1.2 on 2024-10-12 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle_title', models.CharField(max_length=85)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subtitle',
                'verbose_name_plural': 'Subtitles',
            },
        ),
    ]
