# Generated by Django 5.1.3 on 2024-11-21 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_advertising_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_reporter',
            new_name='NewsReporter',
        ),
    ]
