# Generated by Django 5.1.3 on 2024-11-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_news_reporter_newsreporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
