# Generated by Django 5.1.3 on 2024-11-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_passwordresettoken_delete_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertising',
            old_name='onvan_tabligh',
            new_name='title',
        ),
    ]
